[GLOBAL]
pants_version = "2.21.1"
backend_packages.add = [
  "pants.backend.experimental.go",
]


[golang]
cgo_enabled = false
subprocess_env_vars = [
    'GOPRIVATE=github.com/henri14/simple-module/*',
    'HOME',
]